name: flavour
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 1.0.2
  firebase_analytics: 7.1.1
  firebase_messaging: 9.0.1
  flutter_local_notifications: 5.0.0+1
  logger: 1.0.0

flutter:
  uses-material-design: true

