name: flavour
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 1.2.0
  firebase_analytics: 8.1.0
  firebase_messaging: 10.0.0
  flutter_local_notifications: 7.0.0-dev.1
  logger: 1.0.0
  package_info: 2.0.2


flutter:
  uses-material-design: true

